---
title: "Question 2b"
output: html_document
date: "2024-03-17"
---

```{r}
library(tidyverse)
library(ggplot2)
library(scales)
library(dplyr)
```

```{r}
setwd("C:/Users/ASUS UX534F/Desktop/SIM/y2/ST2195/Coursework/Datasets")
```

```{r}
df_list <- list()
```


```{r}
years <- 1995:2004
```


```{r}
for (year in years) {
  filename <- paste0(year, ".csv")
  file_path <- file.path(getwd(), filename)
  
  if (file.exists(file_path)) {
    df_list[[year]] <- read_csv(file_path, locale = locale(encoding = "latin1"))
  }
}
```

```{r}
df <- bind_rows(df_list)
```


```{r}
planedata_df <- read.csv("C:/Users/ASUS UX534F/Desktop/SIM/y2/ST2195/Coursework/Datasets/plane-data.csv")
```


```{r}
print(class(planedata_df$year))
print(unique(planedata_df$year))
```


```{r}
print(planedata_df[planedata_df$year == 0, ])
```

```{r}
planedata_df$year <- as.numeric(planedata_df$year)
planedata_df <- planedata_df[!is.na(planedata_df$year), ]
```

```{r}
print(unique(planedata_df$year))
```

```{r}
planedata_df <- planedata_df[planedata_df$year != 0, ]
print(unique(planedata_df$year))
```

```{r}
df$average_delay <- (df$ArrDelay + df$DepDelay) / 2
```

```{r}
df_b <- df %>%
  select(TailNum, average_delay) %>%
  left_join(planedata_df %>% select(tailnum, year), by = c("TailNum" = "tailnum"))
```

```{r}
df_b <- df_b[complete.cases(df_b$year), ]
df_b$year <- as.integer(df_b$year)
```

```{r}
missing_values <- sum(is.na(df_b$average_delay) | is.infinite(df_b$average_delay) | is.nan(df_b$average_delay))
if (missing_values > 0) {
  print(paste("There are", missing_values, "missing or infinite values in 'average_delay' column."))
}

missing_values_year <- sum(is.na(df_b$year) | is.infinite(df_b$year) | is.nan(df_b$year))
if (missing_values_year > 0) {
  print(paste("There are", missing_values_year, "missing or infinite values in 'year' column."))
}
```

```{r}
df_b <- df_b[complete.cases(df_b$year, df_b$average_delay), ]
```


```{r}
if (sum(is.na(df_b$average_delay) | is.infinite(df_b$average_delay) | is.nan(df_b$average_delay)) == 0 &&
    sum(is.na(df_b$year) | is.infinite(df_b$year) | is.nan(df_b$year)) == 0) {
  
  df_b$year <- as.integer(df_b$year)
  
  plot(df_b$year, df_b$average_delay, 
       col = "saddlebrown",
       xlab = "Plane Manufacturing Year",
       ylab = "Average Delay (minutes)",
       main = "Average Delay against Plane Manufacturing Year",
       xlim = c(min(df_b$year), max(df_b$year)),
       ylim = c(min(df_b$average_delay), max(df_b$average_delay)),
       pch = 16)
  abline(lm(df_b$average_delay ~ df_b$year), col = "blue")
}
```

