---
title: "Question 2c"
output: html_document
date: "2024-03-23"
---

```{r}
library(data.table)
library(ggplot2)
library(caret)
library(scales)
```


```{r}
load <- function(base_path, years, nrows=NULL) {
  data <- lapply(years, function(year) {
    if (is.null(nrows)) {
      fread(paste0(base_path, year, ".csv"))[, Year := year]
    } else {
      fread(paste0(base_path, year, ".csv"), nrows = nrows)[, Year := year]
    }
  })
  rbindlist(data)
}

```


```{r}
preprocess_data <- function(flightdata, airports_df) {
  flightdata <- merge(flightdata, airport_df, by.x = "Origin", by.y = "iata", all.x = TRUE, suffixes = c("", "_origin"))
  flightdata <- merge(flightdata, airport_df, by.x = "Dest", by.y = "iata", all.x = TRUE, suffixes = c("_origin", ""))
  setnames(flightdata, c("lat_origin", "long_origin", "lat", "long"), c("lat_origin", "long_origin", "lat_dest", "long_dest"))
  return(flightdata)
}
```


```{r}
base_path <- "C:/Users/ASUS UX534F/Desktop/SIM/y2/ST2195/Coursework/Datasets/"
years <- 1995:2004
airport_df <- fread(paste0(base_path, "airports.csv"))

flightdata <- load(base_path, years, nrows = 2000000)

flightdata <- preprocess_data(flightdata, airport_df)

```


```{r}
coefficients <- list()

for (year in years) {
  year_data <- flightdata[Year == year]
  
  if (length(unique(year_data$UniqueCarrier)) > 1) {
    year_data[, UniqueCarrier := as.factor(UniqueCarrier)]

    set.seed(42)
    train_index <- createDataPartition(year_data$Diverted, p = 0.8, list = FALSE)
    train_data <- year_data[trainIndex, ]

    features <- c('DepTime', 'CRSDepTime', 'ArrTime', 'CRSArrTime', 'Distance', 'lat_origin', 'long_origin', 'lat_dest', 'long_dest', 'UniqueCarrier', 'Year')
    formula <- as.formula(paste("Diverted ~", paste(features, collapse = " + ")))

    model <- glm(formula, data = train_data, family = "binomial", control = list(maxit = 100))

    coefs <- broom::tidy(model)
    coefs$year <- year
    coefficients[[as.character(year)]] <- coefs
  }
}
```


```{r}
coefficients_data <- rbindlist(coefficients)
uniquefeatures <- unique(coefficients_data$term)
```

```{r}
for (feature in uniquefeatures) {
  if (feature != "(Intercept)") { 
    complete_data <- merge(data.frame(year = years), coefficients_data[term == feature, ], by = "year", all.x = TRUE)
    complete_data$estimate[is.na(complete_data$estimate)] <- 0

    p <- ggplot(complete_data, aes(x = as.factor(year), y = estimate, group = 1)) +
      geom_line() + geom_point() +
      labs(title = paste("Coefficient of", feature, "over Years"),
           x = "Year", y = "Coefficient") +
      theme_minimal() +
      theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
      scale_y_continuous(labels = function(x) scales::number(x, accuracy = 1e-12))
    print(p)
  }
}

```






